doi_server/config/routes.rb
DoiServer::Application.routes.draw do
  get "dois/index"
  root :to => "dois#index"
  
  devise_for :users

  resources :comments

  resources :urls

  resources :dois

  get 'query_id', to: 'dois#query_id'
  get 'query_label', to: 'dois#query_label'

  

end

doi_server/app/models/url.rb
class Url < ActiveRecord::Base

	# validates :url_text, format: {
	# 	with: /\A(http|ftp):\/\/[a-zA-Z]{2-6}\..*\.[a-zA-Z]{2,6}\z/,
	# 	message: " hey there! the url is not right.."
	# }
	
	# (http|ftp):\/\/[a-zA-Z]{2-6}\..*\.[a-zA-Z]{2,6}\z/

	belongs_to :doi

end

doi_server/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
    
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render action: 'show', status: :created, location: @url }
      else
        format.html { render action: 'new' }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:url, :datetime_added, :doi_id)
    end
end

doi_server/app/helpers/urls_helper.rb
module UrlsHelper
end

doi_server/app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= "URL" %><br>
    <%= f.text_field :url_text %>
  </div>
  <div class="field">
    <%= f.label :datetime_added %><br>
    <%= f.datetime_select :datetime_added %>
  </div>
  <%= f.hidden_field :doi_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

doi_server/app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

doi_server/app/views/urls/index.html.erb
<h1>Listing urls</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Url Text</th>
      <th>Datetime-added</th>
      <th>DOI ID</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.url_text %></td>
        <td><%= url.datetime_added.to_s.slice(0..15) %></td>
        <td><%= url.doi_id %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', dois_path %>

doi_server/app/views/urls/new.html.erb
<h1>New url</h1>

<%= render 'form' %>

<%= link_to 'Back', urls_path %>

doi_server/app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @url.url_text %>
</p>

<p>
  <strong>Datetime added:</strong>
  <%= @url.datetime_added %>
</p>

<p>
  <strong>Doi ID:</strong>
  <%= @url.doi_id %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>