doi_server/config/routes.rb
DoiServer::Application.routes.draw do
  get "dois/index"
  root :to => "dois#index"
  
  devise_for :users

  resources :comments

  resources :urls

  resources :dois

  get 'query_id', to: 'dois#query_id'
  get 'query_label', to: 'dois#query_label'

  

end

doi_server/app/models/doi.rb
class Doi < ActiveRecord::Base

	has_many :urls, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	belongs_to :user


	validates :label, :description, presence: true
	

	
	# creates url variable in the doi class
	# so that we can access the url from the 
	# doi view..
	attr_accessor :url_text


end

doi_server/app/controllers/dois_controller.rb
class DoisController < ApplicationController
  before_action :set_doi, only: [:show, :serve, :edit, :update, :destroy]
  # before_filter :authenticate_user!
  
  # GET /dois
  # GET /dois.json
  def index
    @dois = Doi.all
  end

  # GET /dois/1
  # GET /dois/1.json
  def show
  end

  # GET /dois/new
  def new
    @doi = Doi.new
  end

  
  # GET /dois/:id/serve
  def serve
    # when this action recieves a request..
    # grab the parameter params[:id] or 
    # Then redirect the user to the url that 
    # matches that doi
    # redirect_to @doi.urls.last.url_text
  end

  # GET /dois/1/edit
  def edit
  end

  # POST /dois
  # POST /dois.json
  def create
    @doi = Doi.new(doi_params)
    @doi = current_user.dois.create(doi_params)
    #@url = @doi.urls.build(url_params)

    if @doi.save
      @url = Url.new
      @url.doi_id = @doi.id
      @url.url_text = params[:doi][:url_text]
      @url.datetime_added = Time.now
      @url.save
       #time is automatically set somewhere in rails
    end

    # save the paremeters and 
    # => commit to database
    respond_to do |format|
      if @doi.save
        format.html { redirect_to @doi, notice: 'Doi was successfully created.' }
        format.json { render action: 'show', status: :created, location: @doi }
      else
        format.html { render action: 'new' }
        format.json { render json: @doi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dois/1
  # PATCH/PUT /dois/1.json
  def update
    respond_to do |format|
      if @doi.update(doi_params)
        @url = Url.new
        @url.doi_id = @doi.id
        @url.url_text = params[:doi][:url_text]
        @url.save
        format.html { redirect_to @doi, notice: 'Doi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @doi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dois/1
  # DELETE /dois/1.json
  def destroy
    @doi.destroy
    respond_to do |format|
      format.html { redirect_to dois_url }
      format.json { head :no_content }
    end
  end



  def query_id
      doi = Doi.first(:conditions => {:id => params[:query_id]})
      if doi 
          redirect_to doi
      else
        redirect_to root_url, notice: "No match for query <#{params[:query]}> found. The DOI does not exist."
      end
  end

  def query_label
      # doi = Doi.first(:conditions => {:label => params[:query_label]})
      first_doi = Doi.all.map {|doi| doi if Regexp.new(params[:query_label],  Regexp::IGNORECASE).match(doi.label) }.compact.first
        
      if first_doi 
          redirect_to first_doi
      else
        redirect_to root_url, notice: "No match for query <#{params[:query]}> found. The DOI does not exist."
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doi
      @doi = Doi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doi_params
      params.require(:doi).permit(:label, :description, :user_id)
    end

    # def url_params
    #   params.require(:doi).permit(:url_text, :doi_id);
    # end

end

doi_server/app/helpers/dois_helper.rb
module DoisHelper
end

doi_server/app/views/dois/_form.html.erb
<%= form_for(@doi) do |f| %>
  <% if @doi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doi.errors.count, "error") %> prohibited this doi from being saved:</h2>

      <ul>
      <% @doi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% f.hidden_field :user_id %> <!--label  number_field devise sets this from the login.. -->

  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= "Url" %><br>
    <%= f.text_field :url_text %>
    <!-- <input type="text" name="url[url_text]"></input> -->
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

doi_server/app/views/dois/edit.html.erb
<h1>Editing doi</h1>

<%= render 'form' %>

<br>
<%= link_to 'Show', @doi, class: "btn btn-info" %> |
<%= link_to 'Back', dois_path, class: "btn btn-default" %>

doi_server/app/views/dois/index.html.erb
<div class="page-header">DOI Server: </div>




<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= form_tag("/query_id", {method: "get"}) do %>
  <%= label_tag(:query_id, "Search for a DOI by ID: ") %>
  <%= text_field_tag(:query_id) %>
  <%= submit_tag("Search") %>
<% end %>

<%= form_tag("/query_label", {method: "get"}) do %>
  <%= label_tag(:query_label, "Search for a DOI by Label: ") %>
  <%= text_field_tag(:query_label) %>
  <%= submit_tag("Search") %>
<% end %>
<!-- 
<div class="field">
  <input type="text" name="query" id="query" value=""></input>
  <button>Search</button>
</div>
  <br> -->

<h3>DOI List:</h3>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>DOI ID </th> 
      <th>DOI Label </th>  
      <th>Description </th> 
      <th>User  </th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dois.each do |doi| %>
      <tr>
        <td><%= doi.id %></td>
        <td><%= doi.label %></td>
        <td><%= doi.description %></td>
        <td><%= doi.user_id %></td>
        <td><%= doi.urls.last.url_text %></td>

<% if user_signed_in? %>  
        <td><%= link_to 'Show', doi,
                 class: "btn btn-info", style: "height: 26px; padding: 2px 7px 4px 7px; width: 70px" %></td>
        <td>
  <% if current_user.id == doi.user_id %>  
        <%= link_to 'Edit', edit_doi_path(doi),
                class: "btn btn-warning", style: "height: 26px; padding: 2px 7px 4px 7px; width: 70px;" %>
  <% end %>
        </td>
        <td>
        <%= link_to 'Destroy', doi, 
                  method: :delete, data: { confirm: 'Are you sure?' },
                  class: "btn btn-danger", style: "height: 26px; padding: 2px 7px 4px 7px; width: 70px;" %></td>
<% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>  
  <%= link_to new_doi_path, class: "btn btn-primary" do %>
    <span class="glyphicon-plus"></span> New DOI
  <% end %>
<% end %>

<br>
<br>

doi_server/app/views/dois/new.html.erb
<h1>New doi</h1>

<%= render 'form' %>

<%= link_to 'Back', dois_path %>

doi_server/app/views/dois/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>DOI ID:</strong>
  <%= @doi.id %>
</p>

<p>
  <strong>Label:</strong>
  <%= @doi.label %>
</p>

<p>
  <strong>Description:</strong>
  <%= @doi.description %>
</p>

<p>
  <strong>Created By:</strong>
  <%= User.find(@doi.user_id).email %>
</p>

<p>
  <strong>URL:</strong>
  <%= @doi.urls.last.url_text %>
  <%= link_to 'Go To Resource', @doi.urls.last.url_text, class: "btn btn-success" %>
</p>

<%= link_to 'View URL History', urls_path(@doi) %> |
<%= link_to 'View Comments', comments_path %> |
<%= link_to 'Edit', edit_doi_path(@doi) %> |
<%= link_to 'Back', dois_path %>